name: Deploy Server

on:
  workflow_run:
    workflows: ["Docker Build"]
    types: ["completed"]
    branches: ["main", "3-deploy-to-ec2-instance"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Write secrets to instance
        run: echo "${{ secrets.ENV }}" >> .env

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            sudo docker system prune -f
            sudo docker pull ${{ secrets.DOCKERHUB_TAGS }}
            sudo docker stop ${{ vars.CONTAINER_NAME }}
            sudo docker rm -f ${{ vars.CONTAINER_NAME }}
            sudo docker run -d -v ./.env:/app/.env --env-file ./.env --name ${{ vars.CONTAINER_NAME }} ${{ secrets.DOCKERHUB_TAGS }}

      - name: Delete secrets from instance
        run: rm .env
