name: Deploy Server

on:
  workflow_run:
    workflows: ["Docker Build"]
    types: ["completed"]
    branches: ["main", "3-deploy-to-ec2-instance"]

env:
  CONTAINER_NAME: ${{ vars.CONTAINER_NAME }}
  TAG: ${{ secrets.DOCKERHUB_TAGS }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Write secrets to instance
        run: echo "${{ secrets.ENV }}" >> .env

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            sudo docker system prune -f
            sudo docker pull $TAG
            sudo docker stop $CONTAINER_NAME
            sudo docker rm -f $CONTAINER_NAME
            sudo docker run -d -v ./.env:/app/.env --env-file ./.env --name $CONTAINER_NAME $TAG

      - name: Delete secrets from instance
        run: rm .env
